# KNN Implementation

In [23]:
import sklearn.datasets as dt
import numpy as np
from sklearn.metrics import accuracy_score
from collections import Counter

In [29]:
iris = dt.load_iris()
X = iris.data
Y = iris.target

In [31]:
X[34:67], Y[34:67]

(array([[4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5]]),
 array([

In [25]:
from sklearn import model_selection as ms

In [26]:
xtrain, xtest, ytrain, ytest = ms.train_test_split(X, Y)
xtrain.shape, ytrain.shape, xtest.shape, ytest.shape

((112, 4), (112,), (38, 4), (38,))

In [27]:
class KNN_Neighbor:
    
    def __init__(self, xtrain, ytrain, k = 0):
        self.xtrain = xtrain
        self.ytrain = ytrain
        self.k = k
        return
    
    def predict_one(self, xtest):
        distances = []
        for i in range(len(self.xtrain)):
            distance = ((self.xtrain[i, :] - xtest)**2).sum()
            distances.append([distance, i])
        distances = sorted(distances)
        k_neighbours = []
        print("For xtest : ")
        pprint(xtest)
        print(" ---> ")
        for i in range(self.k):
            k_neighbours.append(self.ytrain[distances[i][1]])
            print(f"{[distances[i][0]]}, {[distances[i][1]]}")
            
        print("---------------------------------------------")
        return Counter(k_neighbours).most_common(1)[0][0]
    
    def predict(self, xtest_data):
        ypred = []
        for xtesti in xtest_data:
            ypred.append(self.predict_one(xtesti))
        return ypred

In [28]:
k = int(input('Enter the no of neighbors to choose :'))
clf = KNN_Neighbor(xtrain, ytrain, k)
Ypred = clf.predict(xtest)
accuracy_score(ytest, Ypred)

Enter the no of neighbors to choose :6
For xtest : 
array([7. , 3.2, 4.7, 1.4])
 ---> 
[0.07000000000000003], [22]
[0.10999999999999995], [72]
[0.18999999999999984], [106]
[0.2700000000000005], [65]
[0.29000000000000026], [37]
[0.4099999999999997], [41]
---------------------------------------------
For xtest : 
array([4.8, 3.1, 1.6, 0.2])
 ---> 
[0.01999999999999995], [10]
[0.020000000000000122], [38]
[0.030000000000000124], [103]
[0.050000000000000086], [39]
[0.050000000000000086], [68]
[0.06000000000000008], [77]
---------------------------------------------
For xtest : 
array([5.5, 2.4, 3.7, 1. ])
 ---> 
[0.01999999999999995], [59]
[0.12000000000000022], [75]
[0.18999999999999995], [42]
[0.25999999999999984], [8]
[0.2599999999999999], [90]
[0.33999999999999964], [54]
---------------------------------------------
For xtest : 
array([6. , 2.2, 5. , 1.5])
 ---> 
[0.18999999999999972], [15]
[0.26999999999999996], [43]
[0.2900000000000001], [11]
[0.33999999999999975], [84]
[0.42999999999

0.9473684210526315